# Generated by Django 4.0.1 on 2022-01-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshort',
            options={'verbose_name': 'Краткое описание фильма', 'verbose_name_plural': 'Краткое описание фильмов'},
        ),
        migrations.AlterField(
            model_name='movieshort',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewaggregator.moviefull', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Сообщение'),
        ),
    ]
