# Generated by Django 4.0.1 on 2022-01-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0002_alter_movieshort_options_alter_movieshort_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
    ]
