# Generated by Django 4.0.1 on 2022-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0003_remove_actor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
