# Generated by Django 4.0.1 on 2022-01-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0006_alter_actor_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthday',
        ),
    ]
