# Generated by Django 4.0.1 on 2022-01-23 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0007_remove_actor_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
