# Generated by Django 4.0.1 on 2022-02-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0009_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Гости', 'verbose_name_plural': 'Гости'},
        ),
    ]
