# Generated by Django 4.0.1 on 2022-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0010_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=5000, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
