# Generated by Django 4.0.1 on 2022-02-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0011_guest_delete_user_alter_reviews_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Selfdata',
        ),
        migrations.AlterModelOptions(
            name='selfdata',
            options={'verbose_name': 'Личные данные', 'verbose_name_plural': 'Личные данные'},
        ),
    ]
