# Generated by Django 4.0.1 on 2022-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0012_rename_guest_selfdata_alter_selfdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
        migrations.AddField(
            model_name='moviefull',
            name='age',
            field=models.PositiveIntegerField(default=0, max_length=100, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='moviefull',
            name='lenth',
            field=models.PositiveIntegerField(default=1900, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='moviefull',
            name='rating',
            field=models.CharField(default='', max_length=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='moviefull',
            name='ratingimdb',
            field=models.PositiveIntegerField(default=0, max_length=100, verbose_name='Рейтинг IMDb'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='mark',
            field=models.PositiveIntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.CharField(max_length=100, verbose_name='Фильм'),
        ),
    ]
