# Generated by Django 4.0.1 on 2022-02-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0013_alter_reviews_options_remove_reviews_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefull',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='moviefull',
            name='lenth',
            field=models.PositiveIntegerField(default=0, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='moviefull',
            name='ratingimdb',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг IMDb'),
        ),
    ]
