# Generated by Django 4.0.1 on 2022-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0014_alter_moviefull_age_alter_moviefull_lenth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviefull',
            name='lenth',
        ),
        migrations.AddField(
            model_name='moviefull',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Часы'),
        ),
        migrations.AddField(
            model_name='moviefull',
            name='minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Минуты'),
        ),
    ]
