# Generated by Django 4.0.1 on 2022-03-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewaggregator', '0015_remove_moviefull_lenth_moviefull_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
